name: "grafana"
arch: "amd64"
platform: "linux"
version: "1.15"
section: "default"
priority: "extra"
replaces:
- grafana
provides:
- grafana-server
- grafana-cli
depends:
- adduser
maintainer: "<contact@grafana.com>"
description: |
  Grafana
vendor: "Grafana"
homepage: "https://grafana.com"
license: "Apache 2"
contents:
  - src: ./public
    dst: /usr/share/grafana/public
  - src: ./plugins-bundled
    dst: /usr/share/grafana/plugins-bundled
  - src: ./conf/sample.ini
    dst: /etc/grafana/grafana.ini
  - src: ./conf/
    dst: /usr/share/grafana/conf/
  - src: ./conf/
    dst: /etc/grafana/conf/
  - src: ./bin/grafana-server
    dst: /usr/sbin/grafana-server
  - src: ./bin/grafana-cli
    dst: /usr/sbin/grafana-cli
  - src: ./packaging/deb/init.d/grafana-server
    dst: /etc/init.d/grafana-server
    type: config
  - src: ./packaging/deb/default/grafana-server
    dst: /etc/default/grafana-server
    type: config
  - src: ./packaging/deb/systemd/grafana-server.service
    dst: /usr/lib/systemd/system/grafana-server.service
    type: config
  - src: ./provision/plugins.yaml
    dst: /etc/grafana/provisioning/plugins/plugins.yaml
    type: config
overrides:
  rpm:
    scripts:
      preinstall: ./scripts/preinstall.sh
      postremove: ./scripts/postremove.sh
  deb:
    scripts:
      postinstall: ./packaging/deb/control/postinst
